config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy', as: 'logout'
  resources :sessions, only: [:create, :destroy]

  resources :users, except: [:index] do
    get '/feed' => 'users#feed', as: 'feed'
    get '/friends' => 'users#friends', as: 'friends'
    get '/confirm_deletion' => 'users#confirm_deletion', as: 'confirm_deletion'
  end


  get '/search_friends' => 'users#search', as: 'search_friends'
  get '/search_friends_autocomplete' => 'users#search_autocomplete', as: 'search_friends_autocomplete'

  resources :friendships, only: [:create, :destroy]

  resources :friend_requests, only: [:index, :create, :destroy] do
    member do
      post 'accept'
      post 'reject'
    end
  end

  resources :getaways do
    get '/new_activity/:category' => 'activities#new', as: 'new_activity'
    get '/choose_date'            => 'getaways#choose_date', as: 'choose_date'
    post '/copy'                  => 'getaways#copy', as: 'copy'
    get '/add_comment'            => 'getaways#add_comment', as: 'add_comment'
    put '/update_comment'         => 'getaways#update_comment', as: 'update_comment'
    resources :getaway_photos, only: [:new, :index]
  end

  resources :getaway_photos, except: [:new, :index] do
  end

  resources :activities, only: [:index, :create, :destroy] do
    get '/change_photo'           => 'activities#change_photo', as: 'change_photo'
    put '/update_photo'           => 'activities#update_photo', as: 'update_photo'

    get '/change_comment'         => 'activities#change_comment', as: 'change_comment'
    put '/update_comment'         => 'activities#update_comment', as: 'update_comment'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_attached_file :avatar, :default_url => 'missing.png'
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]


  has_many :getaways, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :friends, :through => :friendships
  has_many :friend_requests, dependent: :destroy

  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  validates :email, :first_name, :last_name, :password_confirmation, :password, presence: true
  validates :email, uniqueness: true

  validates :password, length: { minimum: 8 }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, except: [:new, :create]
  before_action :authorize, only: [:feed]

  def feed
    @user = User.find(params[:user_id])
    @friends = @user.friends
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)

    if @user.save
      session[:current_user] = @user.id

      # if user info is correct redirect user new route
      render :js => "window.location = '#{user_feed_path @user}'"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(users_params)
  end

  def confirm_deletion
    @user = User.find(params[:user_id])
  end

  def destroy
    session[:current_user] = nil
    User.find(params[:id]).destroy
    redirect_to root_path
  end

  def search
    names = params[:search].split(' ')
    @users = User.where("(LOWER(first_name) LIKE '%#{params[:search]}%') OR (LOWER(last_name) LIKE '%#{params[:search]}%')")
    if @users.count == 0
      @users = User.where("first_name='#{names.first}' AND last_name='#{names.last}'")
    end
  end

  def search_autocomplete
    @users = User.where("(LOWER(first_name) LIKE '#{params[:data][:search]}%') OR (LOWER(last_name) LIKE '#{params[:data][:search]}%')")
    @names = {names: []}

    @users.each do |user|
      @names[:names] << "#{user.first_name} #{user.last_name}"
    end

    render json: @names
  end

  def friends
    @friends = User.find(params[:user_id]).friends
  end

  private
  def users_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :comment, :avatar)
  end
end

app/views/users/_form.html.erb
<%= form_for user, :html => { :multipart => true }, remote: true, authenticity_token: true do |f| %>
  <%= f.text_field :first_name, placeholder: 'first name' %>
  <%= f.text_field :last_name, placeholder: 'last name' %>
  <%= f.text_field :email, placeholder: 'email' %>
  <%= f.password_field :password, placeholder: 'password' %>
  <%= f.password_field :password_confirmation, placeholder: 'password confirmation' %>
  <%= f.text_area :comment %>
  <%= f.file_field :avatar %>

  <%= f.submit 'Submit', :class => "form-submit" %>
<% end %>

app/views/users/_timeline.html.erb
<div class="timeline-block" data-id="<%= getaway.id %>">
  <div class="timeline-image">
    <%= image_tag "circle-purple.png" %>
  </div>
  <div class="timeline-content">
    <h3><%= getaway.city %>, <%= getaway.country %></h3>
    <p><%= getaway.comment %></p><button class="read-more">Read more</button>
    <span class="timeline-date"><%= getaway.departure_date.strftime("%m.%Y") %></span>
  </div>
</div>

app/views/users/_user.html.erb
<div id="<%=dom_id(user)%>" class="user">
  <p class="name">
    <%= image_tag user.avatar.url %>

    <%= link_to user.first_name + ' ' + user.last_name, user_path(user) %>

    <% if user.friend_requests.find_by(sender_id: current_user.id) %>

      <p>Awaiting Approval</p>

    <% elsif current_friend_request = current_user.friend_requests.find_by(sender_id: user.id) %>

      <div id="accept-button">
        <%= form_tag accept_friend_request_path(current_friend_request), method: :post, remote: true do %>
          <%= hidden_field_tag 'friend_request_id', current_friend_request.id %>
          <%= submit_tag "Accept Request" %>
        <% end %>
      </div>

      <div id="deny-button">
        <%= form_tag reject_friend_request_path(current_friend_request), method: :post, remote: true do %>
          <%= hidden_field_tag 'friend_request_id', current_friend_request.id %>
          <%= submit_tag "Deny Request" %>
        <% end %>
      </div>

    <% elsif !user.friends.include?(current_user) && user != current_user %>

      <%= form_tag friend_requests_path, method: :post, remote: true do %>
        <%= hidden_field_tag "friend_request[user_id]", user.id  %>
        <%= hidden_field_tag "friend_request[sender_id]", current_user.id %>
        <div class='button'>
          <%= submit_tag "Add Friend" %>
        </div>
      <% end %>

    <% end %>
  </p>
</div>

app/views/users/confirm_deletion.js.erb
var profileModalInner = $('#profile-modal')

profileModalInner.empty();
profileModalInner.append('<button class="close">close</button>');

var deleteText = $('<div class="delete-text">Are you sure you want to delete your account? Your friends will miss you!</div>');
profileModalInner.append(deleteText);
var deleteButton = '<%= button_to "Delete", user_path(@user), method: :delete %>'

profileModalInner.append(deleteButton);

// show the modal using it's container
$('.modal').fadeIn('fast');

app/views/users/create.js.erb
var errorsList = $('<ul>')
$('#sign-up-modal h1').after(errorsList);

<% @user.errors.full_messages.each do |message| %>
  $('<li>').text('<%= j(message) %>').appendTo(errorsList);
<% end %>

app/views/users/destroy.js.erb
var profileModalInner = $('#profile-modal')

profileModalInner.empty();
profileModalInner.append('<button class="close">close</button>');

var deleteFormHtml = '<%= j(render partial: "form", locals: {user: @user}) %>'

profileModalInner.append(deleteFormHtml);

// show the modal using it's container
$('.modal').fadeIn('fast');

app/views/users/edit.js.erb
var profileModalInner = $('#profile-modal')

profileModalInner.empty();
$('.modal').append('<button class="close">close</button>');

var editFormHtml = '<%= j(render partial: "form", locals: {user: @user}) %>'

profileModalInner.append(editFormHtml);

// show the modal using it's container
$('.modal').fadeIn('fast');

app/views/users/feed.html.erb
    <div class="modal">
      <div id="feed-modal"></div>
    </div>

    <div id="user-feed-bg"></div>

    <section id="user-feed" class="container">
      <header id="user-feed-header">
        <div class="grid_3"><h1>Where have your friends been?</h1></div>
        <div class="grid_1 log-trip-cta">
          <h2>Log your own trip</h2>
          <%= link_to(new_getaway_path) do %>
            <div class="feed-log-trip"></div>
          <% end %>
        </div>
      </header>

        <% @friends.each do |friend| %>
          <% friend.getaways.each do |getaway| %>
            <div id="feed" class="grid_3">
              <ul>
                <li>
                  <div class="feed-content">
                    <div class="feed-user-profile-photo">
                      <%= image_tag getaway.user.avatar.url %>
                    </div>
                    <div class="feed-user-trip-details">
                      <h3>
                        <%= getaway.user.first_name %>
                        <%= getaway.user.last_name %>
                      </h3>
                      <h5>
                          <%= getaway.city %>,
                          <%= getaway.country %>
                      </h5>
                      <p>
                        <%= getaway.comment %>
                        <a href="/getaways/<%= getaway.id %>">Explore <%= getaway.user.first_name %>'s trip</a>
                      </p>
                    </div>
                  </div>
                </li>
              </ul>
            </div>
          <% end %>
        <% end %>
    </section>

    <div id="feed-utilities">
      <div id="search-div">
        <%= form_tag('/search_friends', remote: true, method: :get) do %>
            <%= text_field_tag :search %>
            <%= submit_tag 'Search Friends' %>
        <% end %>
      </div>
    </div>

app/views/users/friends.js.erb
var profileModal = $('#profile-modal')
var friends = '';

profileModal.empty();
profileModal.append('<button class="close">close</button>');

<% @friends.each do |friend| %>
  friends += '<%= j(render partial: "user", locals: {user: friend}) %>';
<% end %>

if (!friends) {
  friends = 'You don\'t have any friends';
}

profileModal.append(friends);
$('.modal').fadeIn('fast');

app/views/users/new.js.erb
$('#sign-up-modal').empty();
$('#user-auth-modal').fadeOut('fast');

$('.modal').show();
$('#sign-up-modal').append('<button class="close">Close</button>').append('<h1>Sign Up</h1>');
$('#sign-up-modal').append('<%= j(render partial: "form", locals: {user: @user}) %>');

$('#sign-up-modal').fadeIn('fast');

app/views/users/search.js.erb
var modal = $('.modal');
var closeButton = $('<button class="close">Close</button>');
var feedModal = $('#feed-modal')
var friends = $('<%= j(render @users) %>')

feedModal.empty();
feedModal.append(closeButton);

<% if @users.count == 0 %>
  feedModal.append('<h2>No Results</h2>');
<% else %>
  feedModal.append(friends);
<% end %>
modal.fadeIn('fast');

app/views/users/show.html.erb
<div class="modal">
  <div id="profile-modal">
  </div>
</div>

<section id="user-profile" class="container">
  <header id="user-profile-header" class="grid_3">
    <figure class="profile-photo"><%= image_tag @user.avatar.url %></figure>
    <h1 id="user-name"><%= @user.first_name  %> <%= @user.last_name %></h1>
    <p><%= @user.comment %></p>

    <% if current_user == @user %>
      <a data-remote="true" href="<%= edit_user_path(@user) %>">
        <button class="edit-profile-button">Edit Profile</button>
      </a>
      <a data-remote="true" href="<%= user_confirm_deletion_path(@user) %>">
        <button class="delete-profile-button">Delete Profile</button>
      </a>
    <% end %>

  </header>
  <div id="user-info" class="grid_1">
    <p id="user-email"><%= @user.email %></p>
    <% if current_user == @user %>
      <h2><%= link_to "My News Feed", user_feed_path(@user) %><h2>
      <h2><%= link_to 'My Friends', user_friends_path(@user), remote: true %></h2>
      <h2><%= link_to "Friend Requests (#{@user.friend_requests.count})", friend_requests_path, remote: true %></h2>
    <% else %>
      <h2><%= link_to 'Friends', user_friends_path(@user), remote: true %></h2>
    <% end %>
  </div>

  <section id="timeline" class="grid_4">
    <h1 id="user-trips-heading"><%= @user.first_name  %>'s trips</h1>

    <% if current_user == @user %>
      <button class="log-trip">Log a trip</button>
    <% end %>

    <% @user.getaways.order(departure_date: :desc).each do |getaway| %>
      <%= render partial: 'timeline', locals: {getaway: getaway} %>
    <% end %>

  </section>

</section>

app/views/users/update.js.erb
$('.modal').fadeOut('fast');

$('#user-name').text('<%= @user.first_name %> <%= @user.last_name %>');
$('#user-email').text('<%= @user.email %>');
$('#user-trips-heading').text('<%= @user.first_name %>\'s trips');