config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy', as: 'logout'
  resources :sessions, only: [:create, :destroy]

  resources :users, except: [:index] do
    get '/feed' => 'users#feed', as: 'feed'
    get '/friends' => 'users#friends', as: 'friends'
    get '/confirm_deletion' => 'users#confirm_deletion', as: 'confirm_deletion'
  end


  get '/search_friends' => 'users#search', as: 'search_friends'
  get '/search_friends_autocomplete' => 'users#search_autocomplete', as: 'search_friends_autocomplete'

  resources :friendships, only: [:create, :destroy]

  resources :friend_requests, only: [:index, :create, :destroy] do
    member do
      post 'accept'
      post 'reject'
    end
  end

  resources :getaways do
    get '/new_activity/:category' => 'activities#new', as: 'new_activity'
    get '/choose_date'            => 'getaways#choose_date', as: 'choose_date'
    post '/copy'                  => 'getaways#copy', as: 'copy'
    get '/add_comment'            => 'getaways#add_comment', as: 'add_comment'
    put '/update_comment'         => 'getaways#update_comment', as: 'update_comment'
    resources :getaway_photos, only: [:new, :index]
  end

  resources :getaway_photos, except: [:new, :index] do
  end

  resources :activities, only: [:index, :create, :destroy] do
    get '/change_photo'           => 'activities#change_photo', as: 'change_photo'
    put '/update_photo'           => 'activities#update_photo', as: 'update_photo'

    get '/change_comment'         => 'activities#change_comment', as: 'change_comment'
    put '/update_comment'         => 'activities#update_comment', as: 'update_comment'
  end

end

app/models/getaway.rb
class Getaway < ActiveRecord::Base
  belongs_to :user
  has_many :getaway_photos

  has_many :activities

  validates :departure_date, :user_id, presence: true
  validates :user_id, numericality: { greater_than: 0 }

end

app/controllers/getaways_controller.rb
class GetawaysController < ApplicationController

  def new
    @getaway = Getaway.new
  end

  def create
    @getaway = Getaway.create!(getaways_params)
    redirect_to getaway_path(@getaway)
  end

  def show
    @getaway = Getaway.find(params[:id])
    @random_photo_url = 'none'

    if @getaway.getaway_photos.count > 0
      @random_photo_url = @getaway.getaway_photos.sample.photo.url
    end

    @stay_activities = @getaway.activities.where(category: 'stay')
    @eat_activities = @getaway.activities.where(category: 'eat')
    @play_activities = @getaway.activities.where(category: 'play')
  end

  def edit
    @getaway = Getaway.find(params[:id])
  end

  def update
    @getaway = Getaway.find(params[:id])
    @getaway.update(getaways_params)
    if @getaway.save
      redirect_to getaway_path(@getaway)
    else
      render :edit
    end
  end

  def destroy
    @user = current_user
    @getaway = Getaway.find(params[:id])
    @getaway.destroy
    redirect_to user_path(@user)
  end

  def choose_date
    @getaway = Getaway.find(params[:getaway_id])
  end

  def add_comment
    @getaway = Getaway.find(params[:getaway_id])
  end

  def update_comment
    @getaway = Getaway.find(params[:getaway_id])
    @getaway.comment = params[:new_comment]
    @getaway.save
  end

  def copy
    # copying over a getaway from one user to another
    @getaway = Getaway.find(params[:getaway_id])
    new_getaway = @getaway.dup
    new_getaway.departure_date = params[:new_date]
    new_getaway.comment = nil
    new_getaway.save

    @getaway.activities.each do |activity|
      new_activity = activity.dup
      new_activity.comment = nil
      new_activity.image_url = 'http://images.fineartamerica.com/images-medium-large/palm-tree-silhouettes-sunset-waikiki-natural-selection-craig-tuttle.jpg'
      new_activity.save

      new_getaway.activities << new_activity
    end

    current_user.getaways << new_getaway

    redirect_to getaway_path(new_getaway)
  end

  def getaways_params
    params.require(:getaway).permit(:city, :country, :comment, :departure_date, :user_id)
  end
end

app/views/getaways/_choosedate.html.erb
<%= form_tag getaway_copy_path(getaway) do %>
  <%= date_field_tag 'new_date' %>
  <%= submit_tag 'Set' %>
<% end %>

app/views/getaways/_commentform.html.erb
<%= form_tag getaway_update_comment_path(getaway), method: :put, remote: true do %>
  <%= text_area_tag :new_comment, nil, placeholder: 'What do you have to say?' %>
  <%= submit_tag 'Add Comment' %>
<% end %>

app/views/getaways/_editform.html.erb
<%= text_field_tag 'autocomplete', nil, placeholder: 'Where did you go?' %>

<%= form_tag getaway_path(getaway), id: 'new-getaway-date-form', method: :put do %>
  <div id="departure-date-div">
    <%= date_field :getaway, :departure_date, value: Date.today %>
  </div>

  <div id="comment-div">
    <%= text_area_tag 'getaway[comment]', nil, placeholder: 'What do you have to say?' %>
  </div>

  <%= hidden_field_tag 'getaway[user_id]', current_user.id %>

<% end %>

<h1 id="date-placeholder">When did you go?</h1>
<h1 id="comment-placeholder">What do you have to say?</h1>

app/views/getaways/_form.html.erb
<%= text_field_tag 'autocomplete', nil, placeholder: 'Where did you go?' %>

<%= form_tag getaways_path, id: 'new-getaway-date-form', method: :post do %>
  <div id="departure-date-div">
    <%= date_field :getaway, :departure_date, value: Date.today %>
  </div>

  <div id="comment-div">
    <%= text_area_tag 'getaway[comment]', nil, placeholder: 'What do you have to say?' %>
  </div>

  <%= hidden_field_tag 'getaway[user_id]', current_user.id %>

<% end %>

<h1 id="date-placeholder">When did you go?</h1>
<h1 id="comment-placeholder">What do you have to say?</h1>

app/views/getaways/add_comment.js.erb
var activityModal = $('#activity-modal');

activityModal.empty();
activityModal.append('<button class="close">close</button>');

activityModal.append('<%= j(render partial: "commentform", locals: {getaway: @getaway}) %>');

$('.modal').fadeIn('fast');

app/views/getaways/choose_date.js.erb
var activityModal = $('#activity-modal');

activityModal.empty();
activityModal.append('<button class="close">Close</button>');
activityModal.append('<%= j(render partial: "getaways/choosedate", locals: {getaway: @getaway}) %>');

$('.modal').fadeIn('fast');

app/views/getaways/create_getaway.js.erb
console.log('this works');
$.post('<%= getaways_path %>', place, funtion(data) {
  console.log('hello');
});

app/views/getaways/edit.js.erb
var activityModal = $('#activity-modal');

activityModal.empty();
activityModal.append('<button class="close">Close</button>');

<% if @category == 'play' %>
  activityModal.css('background', '#beb58a')
<% elsif @category == 'stay' %>
  activityModal.css('background', '#29666f')
<% else @category == 'eat' %>
  activityModal.css('background', '#ff3e4d')
<% end %>

activityModal.append('<%= j(render partial: "editform", locals: {getaway: @getaway}) %>');

if (activityModal.find('.new-autocomplete').length === 0) {
  activityModal.find('#autocomplete').replaceWith($('.new-autocomplete'));
  $('.new-autocomplete').show();
}

$('.modal').fadeIn('fast');

app/views/getaways/new.html.erb
<section id="log-getaway">
<%= render partial: 'form' %>
</section>

<div class="modal">
  <div id="new-getaway-modal"></div>
</div>

app/views/getaways/show.html.erb
<section id="trip-detail" class="container">
  <header data-randomphotourl="<%= @random_photo_url %>" class="grid_4 trip-header">
    <figure class="profile-photo">
      <%= image_tag @getaway.user.avatar.url %>
    </figure>
    <h1><%= @getaway.city %>, <%= @getaway.country %></h1>
    <h2><%= @getaway.user.first_name %> <%= @getaway.user.last_name %></h2>

    <div class="getaway-nav">
      <% if @getaway.user != current_user %>
        <a data-remote="true" href="<%= getaway_choose_date_path(@getaway) %>">
          Save as Itinerary
        </a>
      <% end %>

      <% if current_user.getaways.include?(@getaway) %>
        <a data-remote="true" href="<%= new_getaway_getaway_photo_path(@getaway) %>">
          Add Photo
        </a>
      <% end %>

      <a data-remote="true" href="<%= getaway_getaway_photos_path(@getaway) %>">
        View Photos
      </a>

    <% if current_user.getaways.include?(@getaway) %>
      <a data-remote="true" href="<%= edit_getaway_path(@getaway) %>">
        Edit Getaway
      </a>

      <%= link_to "Delete Getaway", getaway_path(@getaway), method: 'delete' %>
    <% end %>

      <% if @getaway.departure_date > Date.today %>
        <h2>Departure: <%= @getaway.departure_date.strftime('%m.%d.%Y') %></h2>
      <% else %>
        <h2><%= @getaway.departure_date.strftime('%m.%Y') %></h2>
      <% end %>
    </div>
  </header>

  <section id="trip-info">
    <div class="grid_4">
      <% if @getaway.comment %>
        <p class="trip-story"><%= @getaway.comment %></p>
      <% elsif !current_user.getaways.include?(@getaway) %>
        <p class="trip-story"><%= @getaway.user.first_name %> has not commented yet.</p>
      <% else %>
        <div id="getaway-comment-button">
          <a data-remote="true" href="<%= getaway_add_comment_path(@getaway) %>">
            <button name="button">What do you have to say?</button>
          </a>
        </div>
      <% end %>
    </div>
    <div class="grid_3_1_first omega stayed">
      <% if @getaway.departure_date > Date.today %>
        <h3>Places to stay.</h3>
      <% else %>
        <h3>Where I stayed.</h3>
      <% end %>
      <% if current_user.getaways.include?(@getaway) %>
        <div class="add-cta">
          <a data-remote="true" href="<%= getaway_new_activity_path(@getaway.id, 'stay') %>">
            <div class="add-stayed"></div>
          </a>
          <p>Add a place</p>
        </div>
      <% end %>
      <div style="clear: both;"></div>

      <ul class="trip-info-list">
        <% @stay_activities.each do |activity| %>
          <%= render partial: 'activities/activity', locals: {getaway: @getaway, activity: activity} %>
        <% end %>
      </ul>
    </div>
    <div class="grid_3_1 alpha omega ate">
      <% if @getaway.departure_date > Date.today %>
        <h3>Places to eat.</h3>
      <% else %>
        <h3>Where I ate.</h3>
      <% end %>

      <% if current_user.getaways.include?(@getaway) %>
        <div class="add-cta">
          <a data-remote="true" href="<%= getaway_new_activity_path(@getaway.id, 'eat') %>">
            <div class="add-restaurant"></div>
          </a>
          <p>Add a restaurant</p>
        </div>
      <% end %>

      <div style="clear: both;"></div>
      <ul class="trip-info-list">
        <% @eat_activities.each do |activity| %>
          <%= render partial: 'activities/activity', locals: {getaway: @getaway, activity: activity} %>
        <% end %>
      </ul>
    </div>

    <div class="grid_3_1_last alpha played">
      <% if @getaway.departure_date > Date.today %>
        <h3>Things to do.</h3>
      <% else %>
        <h3>Where I played.</h3>
      <% end %>

      <% if current_user.getaways.include?(@getaway) %>
        <div class="add-cta">
          <a data-remote="true" href="<%= getaway_new_activity_path(@getaway.id, 'play') %>">
            <div class="add-activity"></div>
          </a>
          <p>Add a activity</p>
        </div>
      <% end %>

      <div style="clear: both;"></div>
      <ul class="trip-info-list">
        <% @play_activities.each do |activity| %>
          <%= render partial: 'activities/activity', locals: {getaway: @getaway, activity: activity} %>
        <% end %>
      </ul>
    </div>
  </section>
</section>

<div class="modal">
  <div id="activity-modal">
  </div>
</div>
<input style="display: none" class="new-autocomplete" id="autocomplete" name="autocomplete" placeholder="Where did you go?" type="text">

app/views/getaways/update_comment.js.erb
$('.modal').fadeOut();

var getawayCommentButton = $('#getaway-comment-button');

getawayCommentButton.replaceWith('<p class="trip-story"><%= @getaway.comment %></p>')