config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy', as: 'logout'
  resources :sessions, only: [:create, :destroy]

  resources :users, except: [:index] do
    get '/feed' => 'users#feed', as: 'feed'
    get '/friends' => 'users#friends', as: 'friends'
    get '/confirm_deletion' => 'users#confirm_deletion', as: 'confirm_deletion'
  end


  get '/search_friends' => 'users#search', as: 'search_friends'
  get '/search_friends_autocomplete' => 'users#search_autocomplete', as: 'search_friends_autocomplete'

  resources :friendships, only: [:create, :destroy]

  resources :friend_requests, only: [:index, :create, :destroy] do
    member do
      post 'accept'
      post 'reject'
    end
  end

  resources :getaways do
    get '/new_activity/:category' => 'activities#new', as: 'new_activity'
    get '/choose_date'            => 'getaways#choose_date', as: 'choose_date'
    post '/copy'                  => 'getaways#copy', as: 'copy'
    get '/add_comment'            => 'getaways#add_comment', as: 'add_comment'
    put '/update_comment'         => 'getaways#update_comment', as: 'update_comment'
    resources :getaway_photos, only: [:new, :index]
  end

  resources :getaway_photos, except: [:new, :index] do
  end

  resources :activities, only: [:index, :create, :destroy] do
    get '/change_photo'           => 'activities#change_photo', as: 'change_photo'
    put '/update_photo'           => 'activities#update_photo', as: 'update_photo'

    get '/change_comment'         => 'activities#change_comment', as: 'change_comment'
    put '/update_comment'         => 'activities#update_comment', as: 'update_comment'
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :getaway

  validates :name, :category, :getaway_id, presence: true
  validates :category, inclusion: { in: %w( stay eat play ) }
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
  end

  def new
    @category = params[:category]
    @getaway_id = params[:getaway_id]
    if @category == 'stay'
      @question = 'Where did you stay?'
    elsif @category == 'eat'
      @question = 'Where did you eat?'
    else
      @question = 'What did you do?'
    end
  end

  def create
    @activity = Activity.create(activities_params)

    if !@activity.image_url
      @activity.image_url = 'http://images.fineartamerica.com/images-medium-large/palm-tree-silhouettes-sunset-waikiki-natural-selection-craig-tuttle.jpg'
      @activity.save
    end
  end

  def change_photo
    @activity = Activity.find(params[:activity_id])
  end

  def update_photo
    @activity = Activity.find(params[:activity_id]);
    photo = GetawayPhoto.find(params[:photo_id]);
    @activity.image_url = photo.photo.url
    @activity.save

    render json: @activity
  end

  def change_comment
    @activity = Activity.find(params[:activity_id])
  end

  def update_comment
    @activity = Activity.find(params[:activity_id])
    @activity.comment = params[:new_comment]
    @activity.save
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
  end

  private
  def activities_params
    params.require(:activity).permit(:name, :getaway_id, :category, :comment)
  end
end

app/views/activities/_activity.html.erb
<li id="<%= dom_id(activity) %>" class="activity">
  <figure class="container"><%= image_tag activity.image_url %></figure>


  <p class="activity-name"><%= activity.name %></p>

  <div></div>

  <% if current_user.getaways.include?(getaway) %>
    <%= link_to 'Change Photo', activity_change_photo_path(activity), class: 'activity-photo', remote: true %>
  <% end %>

  <div class="trip-info-detail"><%= activity.comment %></div>

  <% if current_user.getaways.include?(getaway) %>

    <% if activity.comment == nil || activity.comment == "" %>
      <%= link_to 'Add a comment', activity_change_comment_path(activity), class: "add-activity-comment", remote: true %>
    <% end %>

    <div class="delete-wrapper">
      <%= link_to 'Delete', activity_path(activity), method: :delete, remote: true, class: 'remove-activity' %>
    </div>
  <% end %>
</li>

app/views/activities/_commentform.html.erb
<%= form_tag activity_update_comment_path(activity), method: :put, remote: true do %>
  <%= text_area_tag :new_comment, nil, placeholder: 'What do you have to say?' %>
  <%= submit_tag 'Update Comment' %>
<% end %>

app/views/activities/_form.html.erb
<%= form_tag activities_path, method: :post, :class => 'activities-form', remote: true do %>
  <%= hidden_field_tag 'activity[category]', category %>
  <%= hidden_field_tag 'activity[getaway_id]', getaway_id %>
  <%= text_field_tag 'activity[name]', nil, placeholder: question %>
  <%= text_area_tag 'activity[comment]', nil, placeholder: 'What do you have to say?', size: '60x12' %>
  <%= submit_tag 'Add', :class => 'btn-submit' %>
<% end %>

app/views/activities/change_comment.js.erb
var activityModal = $('#activity-modal');

activityModal.empty();
activityModal.append('<button class="close">close</button>')

<% if @activity.category == 'play' %>
  activityModal.css('background', '#beb58a')
<% elsif @activity.category == 'stay' %>
  activityModal.css('background', '#29666f')
<% else @activity.category == 'eat' %>
  activityModal.css('background', '#ff3e4d')
<% end %>

activityModal.append('<%= j(render partial: "commentform", locals: {activity: @activity}) %>');
$('.modal').fadeIn('fast');

app/views/activities/change_photo.js.erb
var activityModal = $('#activity-modal');
var photosDiv = $('<div id="choose-getaway-photo">');

activityModal.empty();
activityModal.append('<button class="close">close</button>');

activityModal.append('<h1>Choose a photo</h1>');
activityModal.append(photosDiv);
photosDiv.append('<%= j(render partial: "getaway_photos/photos", locals: {photos: @activity.getaway.getaway_photos, activity: @activity}) %>');

$('.modal').fadeIn('fast');

app/views/activities/create.js.erb
$('.modal').fadeOut();
var activityList

if ('<%= @activity.category %>' === 'play') {
  activityList = $('.played').find('.trip-info-list');
} else if ('<%= @activity.category %>' === 'stay') {
  activityList = $('.stayed').find('.trip-info-list');
} else if ('<%= @activity.category %>' === 'eat') {
  activityList = $('.ate').find('.trip-info-list');
}

activityList.append('<%= j(render partial: "activities/activity", locals: {getaway: @activity.getaway, activity: @activity}) %>')

app/views/activities/destroy.js.erb
$('#' + '<%= dom_id(@activity) %>').remove();

app/views/activities/new.js.erb
var activityModal = $('#activity-modal');

activityModal.empty();
activityModal.append('<button class="close">close</button>');

<% if @category == 'play' %>
  activityModal.css('background', '#beb58a')
<% elsif @category == 'stay' %>
  activityModal.css('background', '#29666f')
<% else @category == 'eat' %>
  activityModal.css('background', '#ff3e4d')
<% end %>

activityModal.append('<%= j(render partial: "activities/form", locals: {category: @category, getaway_id: @getaway_id, question: @question}) %>')

$('.modal').fadeIn('fast');

app/views/activities/update_comment.js.erb
var activityEl = $('#' + '<%= dom_id(@activity) %>');

activityEl.find('.add-activity-comment').remove();
activityEl.find('.trip-info-detail').text('<%= @activity.comment %>');

$('.modal').fadeOut('fast');