config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get '/login' => 'sessions#new', as: 'login'
  get '/logout' => 'sessions#destroy', as: 'logout'
  resources :sessions, only: [:create, :destroy]

  resources :users, except: [:index] do
    get '/feed' => 'users#feed', as: 'feed'
    get '/friends' => 'users#friends', as: 'friends'
    get '/confirm_deletion' => 'users#confirm_deletion', as: 'confirm_deletion'
  end


  get '/search_friends' => 'users#search', as: 'search_friends'
  get '/search_friends_autocomplete' => 'users#search_autocomplete', as: 'search_friends_autocomplete'

  resources :friendships, only: [:create, :destroy]

  resources :friend_requests, only: [:index, :create, :destroy] do
    member do
      post 'accept'
      post 'reject'
    end
  end

  resources :getaways do
    get '/new_activity/:category' => 'activities#new', as: 'new_activity'
    get '/choose_date'            => 'getaways#choose_date', as: 'choose_date'
    post '/copy'                  => 'getaways#copy', as: 'copy'
    get '/add_comment'            => 'getaways#add_comment', as: 'add_comment'
    put '/update_comment'         => 'getaways#update_comment', as: 'update_comment'
    resources :getaway_photos, only: [:new, :index]
  end

  resources :getaway_photos, except: [:new, :index] do
  end

  resources :activities, only: [:index, :create, :destroy] do
    get '/change_photo'           => 'activities#change_photo', as: 'change_photo'
    put '/update_photo'           => 'activities#update_photo', as: 'update_photo'

    get '/change_comment'         => 'activities#change_comment', as: 'change_comment'
    put '/update_comment'         => 'activities#update_comment', as: 'update_comment'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RetreatApp</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>

  <%= javascript_include_tag 'application' %>
  <%= typekit_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header id="top-bar">
    <div class="container">
      <a href="/"><div class="logo">Retreat</div></a>
      <div class="navigation">
        <ul>

          <% if !current_user %>
            <li>
              <%= link_to 'Log In', login_path, id: 'login-link', remote: true %>
            </li>
          <% else %>
            <li>
              Hi, <%= link_to current_user.first_name, user_path(current_user) %> <span class="nav-space">|</span>
            </li>
            <li>
              <%= link_to "My Feed", user_feed_path(current_user) %> <span class="nav-space">|</span>
            </li>
            <li>
              <%= link_to 'My Getaways', user_path(current_user) %> <span class="nav-space">|</span>
            </li>
            <li>
              <%= link_to 'Log a trip', new_getaway_path(current_user) %> <span class="nav-space">|</span>
            </li>
            <li>
              <%= link_to 'Log Out', logout_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </header>

  <% if !current_user %>
    <div class="modal">
      <div id="user-auth-modal">
      </div>

      <div id="sign-up-modal">
      </div>
    </div>
  <% end %>

<%= yield %>

</body>
</html>